<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    

<title>Bill Sharing&#8482; - Terms Of Service - Privacy Policy</title>


<META Name="keywords" Content="Bill Sharing By My Contact, Bill Sharing, BillSharing.com, Contact ">

<META NAME="Description" Content="Terms Of Service - Privacy Policy. Get paid for every time you receive a call, an email or text message with Bill Sharing&#8482; by my contact&#8482;">

<META NAME="ROBOTS" CONTENT="noINDEX, noFOLLOW">
<META NAME="Revisit" CONTENT="20">
<meta name="language" content="en" />
<meta name="Author" content="Copyright - Bill Sharing by my contact - all rights reserved.">


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/style.css" media="screen">
  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top"><font size="4">
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/#page-top" class="navbar-brand page-scroll"><img src="css/images/do-not-call-my-contact.gif" alt="Bill Sharing from my contact"/></a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <li><a class="page-scroll" href="/#section-0">Sign Up</a></li>
            <li><a class="page-scroll" href="/#section-1">How It Works</a></li>
           <!-- <li><a class="page-scroll" href="#section-3">News</a></li> -->
            <li><a class="page-scroll" href="/#section-4">Contact Us</a></li>
          </ul>
        </div>
      </div>
    </div>


    <section class="section" id="section-1">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
             <h3>Terms of Service and Privacy Policy</h3>
          </div>
<BR><BR>
          <div class="xcol-sm-4">

<BR>
<h2>Terms of Service</h2>
<h4>1. Your Acceptance</h4>
<p>This is an agreement between my contact&#8482;, a business located in Orange County, CA (&ldquo;my contact&quot;), the owner and operator of www.BillSharing.com (the &ldquo;my contact   Site&rdquo;), the my contact Site, the &quot;my contact Service&quot;, or the   &quot;Service&quot;), and you (&ldquo;you&rdquo; or &ldquo;You&rdquo;), a user of the Service. BY USING   THE SERVICE, YOU ACKNOWLEDGE AND AGREE TO THESE TERMS OF SERVICE, AND   MY CONTACT'S PRIVACY POLICY, WHICH CAN BE FOUND AT   http://www.my billsharing.com/tos.asp, AND WHICH ARE INCORPORATED   HEREIN BY REFERENCE. If you choose to not agree with any of these terms,   you may not use the Service. </p>
<h4>2. my contact Service</h4>
<p>These Terms of Service apply to all users of the my contact Service.    Information provided by our users through the my contact Service may   contain links to third party websites that are not owned or controlled   by my contact. my contact has no control over, and assumes no responsibility   for, the content, privacy policies, or practices of any third party   websites. In addition, my contact will not and cannot censor or edit the   content of any third-party site. By using the Service, you expressly   acknowledge and agree that my contact shall not be responsible for any   damages, claims or other liability arising from or related to your use   of any third-party website. </p>
<h4>3. my contact Access</h4>
<p>A. Subject to your compliance with these Terms of Service, my contact   hereby grants you permission to use the Service, provided that: (i) your   use of the Service as permitted is solely for your personal use, and   you are not permitted to resell or charge others for use of or access to   the Service, or in any other manner inconsistent with these Terms of   Service; (ii) you will not duplicate, transfer, give access to, copy or   distribute any part of the Service in any medium without my contact's   prior written authorization; (iii) you will not attempt to reverse   engineer, alter or modify any part of the Service; and (iv) you will   otherwise comply with the terms and conditions of these Terms of Service   and Privacy Policy. </p>
<p>B. In order to access and use the features of the Service, you   acknowledge and agree that you will have to provide my contact with your   email address.  my contact will not be liable for your losses caused by   any unauthorized use of your account, you may be liable for the losses   of my contact or others due to such unauthorized use. </p>
<p>C. You agree not to use or launch any automated system, including   without limitation, &quot;robots,&quot; &quot;spiders,&quot; &quot;offline readers,&quot; etc. or   &quot;load testers&quot; that accesses the Service in a   manner that sends more request messages to the my contact servers in a   given period of time than a human can reasonably produce in the same   period by using a my contact application, and you are forbidden from   ripping the content unless specifically allowed. Notwithstanding the   foregoing, my contact grants the operators of public search engines   permission to use spiders to copy materials from the website for the   sole purpose of creating publicly available searchable indices of the   materials, but not caches or archives of such materials. my contact   reserves the right to revoke these exceptions either generally or in   specific cases. While we don't disallow the use of sniffers such as   Ethereal, tcpdump or HTTPWatch in general, we do disallow any efforts to   reverse-engineer our system, our protocols, or explore outside the   boundaries of the normal requests made by my contact clients. We have to   disallow using request modification tools such as fiddler or whisker, or   the like or any other such tools activities that are meant to explore   or harm, penetrate or test the site. You must secure our permission   before you measure, test, health check or otherwise monitor any network   equipment, servers or assets hosted on our domain. You agree not to   collect or harvest any personally identifiable information, including   phone number, from the Service, nor to use the communication systems   provided by the Service for any commercial solicitation or spam   purposes. You agree not to spam, or solicit for commercial purposes, any   users of the Service. </p>
<h4>4. Intellectual Property Rights</h4>
<p>The design of the my contact Service along with my contact created text,   scripts, graphics, interactive features and the like, except Status   Submissions (as defined below), and the trademarks, service marks and   logos contained therein (&quot;Marks&quot;), are owned by or licensed to my contact,   subject to copyright and other intellectual property rights under   United States and foreign laws and international conventions. The   Service is provided to you AS IS for your information and personal use   only. my contact reserves all rights not expressly granted in and to the   Service.  You agree to not engage in the use, copying, or distribution   of any of the Service other than expressly permitted herein, including   any use, copying, or distribution of Status Submissions of third parties   obtained through the Service for any commercial purposes. </p>
<h4>5.  Warranty Disclaimer</h4>
<p>YOU AGREE THAT YOUR USE OF THE MY CONTACT SERVICE SHALL BE AT YOUR SOLE   RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, MY CONTACT, ITS OFFICERS,   DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR   IMPLIED, IN CONNECTION WITH THE SERVICE AND YOUR USE THEREOF. MY CONTACT   MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR   COMPLETENESS OF THIS SERVICE'S CONTENT AND ASSUMES NO LIABILITY OR   RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT,   (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER,   RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICE, (III) ANY   UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL PERSONAL   INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY   INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICE, (IV)   ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED   TO OR THROUGH OUR SERVICE THROUGH THE ACTIONS OF ANY THIRD PARTY, AND/OR   (V) ANY ERRORS OR OMISSIONSIN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF   ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED,   TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE MY CONTACT SERVICE.   MY CONTACT DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY   FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY   THROUGH THE MY CONTACT SERVICE OR ANY HYPERLINKED WEBSITE OR FEATURED IN   ANY USER STATUS SUBMISSION OR OTHER ADVERTISING, AND MY CONTACT WILL NOT   BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY   TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR   SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY   MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND   EXERCISE CAUTION WHERE APPROPRIATE. AND AGAIN, USE THIS JUST FOR FUN. </p>
<h4>6. Limitation of Liability</h4>
<p>IN NO EVENT SHALL MY CONTACT, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR   AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,   PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I)   ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR   PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO   AND USE OF OUR SERVICE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR   SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL   INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF   TRANSMISSION TO OR FROM OUR SERVERS, (IV) ANY BUGS, VIRUSES, TROJAN   HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE   BY ANY THIRD PARTY,  (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR   ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY   CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA   THE MY CONTACT CLIENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY   OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE   POSSIBILITY OF SUCH DAMAGES, AND/OR (VI) THE DISCLOSURE OF INFORMATION   PURSUANT TO THESE TERMS OF SERVICE OR PRIVACY POLICY. THE FOREGOING   LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY   LAW IN THE APPLICABLE JURISDICTION. </p>
<p>YOU SPECIFICALLY ACKNOWLEDGE THAT MY CONTACT SHALL NOT BE LIABLE FOR   USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY   THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING   RESTS ENTIRELY WITH YOU. </p>
<p>The Service is controlled and offered by my contact from its facilities   in the United States of America. my contact makes no representations that   the my contact Service is appropriate or available for use in other   locations. Those who access or use the my contact Service from other   jurisdictions do so at their own volition and are responsible for   compliance with local law. </p>
<h4>7. Indemnity</h4>
<p>You agree to defend, indemnify and hold harmless my contact, its parent   corporation, officers, directors, employees and agents, from and   against any and all claims, damages, obligations, losses, liabilities,   costs or debt, and expenses (including but not limited to attorney's   fees) arising from: (i) your use of and access to the my contact Service;   (ii) your violation of any term of these Terms of Service; (iii) your   violation of any third party right, including without limitation any   copyright, property, or privacy right; or (iv) any claim that one of   your Status Submissions caused damage to a third party. This defense and   indemnification obligation will survive these Terms of Service and your   use of the my contact Service.  </p>
<h4>8. Ability to Accept Terms of Service</h4>
<p>You affirm that you are either more than 16 years of age, or an   emancipated minor, or possess legal parental or guardian consent, and   are fully able and competent to enter into the terms, conditions,   obligations, affirmations, representations, and warranties set forth in   these Terms of Service, and to abide by and comply with these Terms of   Service. In any case, you affirm that you are at least 16 years old as   the my contact Service is not intended for children under 16. If you are   under 16 years of age, you are not permitted to use the my contact   Service. You further represent and warrant that you are not located in a   country that is subject to a U.S. Government embargo, or that has been   designated by the U.S. Government as a&rdquo; terrorist-supporting&rdquo; country,   and that you are not listed on any U.S. Government list of prohibited or   restricted parties. </p>
<h4>9. Assignment</h4>
<p>These Terms of Service, and any rights and licenses granted   hereunder, may not be transferred or assigned by you, but may be   assigned by my contact without restriction. </p>
<h4>10. General</h4>
<p>You agree that: (i) the my contact Service shall be deemed solely based   in California; (ii) the my contact Service shall be deemed a passive   server that does not give rise to personal jurisdiction over my contact,   either specific or general, in jurisdictions other than California; and   (iii) that you agree to subject to the jurisdiction of California in the   event of any legal dispute. These Terms of Service shall be governed by   the internal substantive laws of the State of California, without   respect to its conflict of laws principles. Any claim or dispute between   you and my contact that arises in whole or in part from the my contact   Service shall be decided exclusively by a court of competent   jurisdiction located in Santa Clara County, California. These Terms of   Service, together with the Privacy Policy at   http://www.my contact.com/tos.asp and any other legal notices   published by my contact, including, but not limited to an end user license   agreement, shall constitute the entire agreement between you and   my contact concerning the my contact Service. If any provision of these   Terms of Service is deemed invalid by a court of competent jurisdiction,   the invalidity of such provision shall not affect the validity of the   remaining provisions of these Terms of Service, which shall remain in   full force and effect. No waiver of any term of this these Terms of   Service shall be deemed a further or continuing waiver of such term or   any other term, and my contact's failure to assert any right or provision   under these Terms of Service shall not constitute a waiver of such right   or provision. my contact reserves the right to amend or modify these   Terms of Service at any time, and it is your responsibility to review   these Terms of Service for any changes. If you do not agree to the   revised Terms, your only recourse is to discontinue the use of the   my contact Service.  Your continued use of the my contact Service following   any amendment of these Terms of Service will signify your assent to and   acceptance of its revised terms. YOU AND MY CONTACT AGREE THAT ANY CAUSE   OF ACTION ARISING OUT OF OR RELATED TO THE MY CONTACT SERVICE MUST   COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES.   OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED. </p>
<br />
<a name="Privacy" id="Privacy"></a>
<h2>Privacy Policy</h2>
<p>my contact  (&quot;my contact&quot;) recognizes that its customers, visitors   and users, want to know what's up with privacy. my contact provides this   Privacy Policy to help you make an informed decision about whether to   use or continue using the my contact Site, my contact Software and/or the   my contact Service.  If you do not agree to our practices, please do not   use the my contact Site, my contact Software,or my contact Service. </p>
<p>This Privacy Policy is incorporated into and is subject to the   my contact Terms of Service. Your use of the my contact Site, my contact   Software and the my contact Service and any personal information you   provide on the my contact Site or my contact Service remains subject to the   terms of this Privacy Policy and our Terms of Service. </p>
<p>Please note that any Status Submissions or other content posted at   the direction or discretion of users of the my contact Service becomes   published content and is not considered personally identifiable   information subject to this Privacy Policy. </p>
<h4>What Does This Privacy Policy Cover?</h4>
<p>This Privacy Policy is part of my contact&rsquo;s Terms of Service and covers   the treatment of user information, including personally identifying   information, obtained by my contact, including information obtained when   you access the my contact&rsquo;s Site, use the my contact Service or any other   software provided by my contact. </p>
<p>This Privacy Policy does not apply to the practices of companies that   my contact does not own or control, or to individuals whom my contact does   not employ or manage, including any of the third parties to which   my contact may disclose user information as set forth in this Privacy   Policy. </p>
<h4>The Information my contact Collects</h4>
<p>my contact may obtain the following types of information from or   concerning you, which may include   information that can be used to identify you as specified below   (&ldquo;Personally Identifying Information&rdquo;): </p>
<p><strong>User Provided Information:</strong> You provide certain   Personally Identifiable Information, such as your mobile phone number,   push notification name (if applicable), billing information (if   applicable) and mobile device information to my contact when choosing to   participate in various uses of the my contact Service, such as registering   as a user.    In order to provide the my contact Service, my contact will periodically   access your address book or contact list on your mobile phone to locate   the mobile phone numbers of other my contact users (&ldquo;in-network&rdquo; numbers),   or otherwise categorize other mobile phone numbers as &ldquo;out-network&rdquo;   numbers, which are stored as one-way irreversibly hashed values. </p>
<p><strong>Cookies Information:</strong> When you visit the my contact   Site, we may send one or more cookies - a small text file containing a   string of alphanumeric characters - to your computer that uniquely   identifies your browser. my contact uses both session cookies and   persistent cookies. A persistent cookie remains after you close your   browser. Persistent cookies may be used by your browser on subsequent   visits to the site. Persistent cookies can be removed by following your   web browser help file directions. A session cookie is temporary and   disappears after you close your browser. You can reset your web browser   to refuse all cookies or to indicate when a cookie is being sent.   However, the my contact Site may not function properly if the ability to   accept cookies is disabled. </p>
<p><strong>Log File Information:</strong> When you use the my contact   Site, our servers automatically record certain information that your web   browser sends whenever you visit any website. These server logs may   include information such as your web request, Internet Protocol (&quot;IP&quot;)   address, browser type, browser language, referring / exit pages and   URLs, platform type, number of clicks, domain names, landing pages,   pages viewed and the order of those pages, the amount of time spent on   particular pages, the date and time of your request, one or more cookies   that may uniquely identify your browser,  the status of and various status information.</p>
<h4>The Way my contact Uses Information</h4>
<p>If you submit Personally Identifiable Information to us through the   my contact Site, or my contact Service, then we use your personal   information to operate, maintain, and provide to you the features and   functionality of the my contact Site and my contact Service.  In particular,   your phone number and/of email address is essential to your use of the my contact   Service and will be retained.   Any Personally Identifiable   Information or status content that you voluntarily disclose on the   my contact Service becomes publicly available and may be collected and   used by other users of the my contact Service. We do not use your mobile   phone number or other Personally Identifiable Information to send   commercial or marketing messages without your consent or except as part   of a specific program or feature for which you will have the ability to   opt-in or opt-out. We may, however, use your mobile phone number (or   email address, if provided) without further consent for non-marketing or   administrative purposes (such as notifying you of major my contact Site   or my contact Service changes or for customer service purposes). We may   use both your Personally Identifiable Information and certain   non-personally-identifiable information (such as anonymous user usage   data, cookies, IP addresses, browser type, clickstream data, etc.) to   improve the quality and design of the my contact Site and my contact Service   and to create new features, promotions, functionality, and services by   storing, tracking, and analyzing user preferences and trends.    We may use cookies and log file information to: (a) remember information   so that you will not have to re-enter it during your visit or the next   time you use the my contact Service or my contact Site; (b) provide custom,   personalized content and information; (c) monitor individual and   aggregate metrics such as total number of visitors, pages viewed, etc.;   and (d) track your entries, submissions, views and such. </p>
<h4>When my contact Discloses Information</h4>
<p>We do not sell or share your Personally Identifiable Information   (such as email address) with other third-party companies for their   commercial or marketing use without your consent or except as part of a   specific program or feature for which you will have the ability to   opt-in or opt-out.  We may share your Personally Identifiable   Information with third party service providers to the extent that it is   reasonably necessary to perform, improve or maintain the my contact   Service. We may share non-personally-identifiable information (such as   anonymous User usage data, referring / exit pages and URLs, platform   types, asset views, number of clicks, etc.) with interested   third-parties to assist them in understanding the usage patterns for   certain content, services, advertisements, promotions, and/or   functionality on the my contact Site. We may collect and release   Personally Identifiable Information and/or non-personally-identifiable   information if required to do so by law, or in the good-faith belief   that such action is necessary to comply with state and federal laws   (such as U.S. Copyright Law), international law or respond to a court   order, subpoena, or search warrant or equivalent, or where in our   reasonable belief, an individual&rsquo;s physical safety may be at risk or   threatened. my contact also reserves the right to disclose Personally   Identifiable Information and/or non-personally-identifiable information   that my contact believes, in good faith, is appropriate or necessary to   enforce our Terms of Service, take precautions against liability, to   investigate and defend itself against any third-party claims or   allegations, to assist government enforcement agencies, to protect the   security or integrity of the my contact Site or our servers, and to   protect the rights, property, or personal safety of my contact, our users   or others. </p>
<h4>Your Choices</h4>
<p>You may, of course, decline to submit Personally Identifiable   Information through the my contact Site or the my contact Service, in which   case my contact may not be able to provide certain services to you.  If   you do not agree with our Privacy Policy or Terms of Service, please   delete your account, uninstall the my contact mobile application and   discontinue use of the my contact Service; your continued usage of the   my contact Service will signify your assent to and acceptance of our   Privacy Policy and Terms of Service. To protect your privacy and   security, we take reasonable steps (such as SMS authentication in   certain cases) to verify your identity before registering your mobile   phone number and granting you access to the my contact Service. Please   contact my contact via email to support at my contact.com or available web   forms with any questions or comments about this Privacy Policy, your   personal information, your consent, or your opt-in or opt-out choices. </p>
<h4>Third-party Advertisers, Links to Other Sites</h4>
<p>my contact is currently ad-free.    We have no intention to introduce advertisement into the product, but   if we ever do, will update this section. </p>
<h4>Our Commitment To Data Security</h4>
<p>my contact uses commercially reasonable physical, managerial, and   technical safeguards to preserve the integrity and security of your   personal information. We cannot, however, ensure or warrant the security   of any information you transmit to my contact and you do so at your own   risk. Using unsecured wifi or other unprotected networks to submit   messages through the my contact Service is never recommended.  Once we   receive your transmission of information, my contact makes commercially   reasonable efforts to ensure the security of our systems. However,   please note that this is not a guarantee that such information may not   be accessed, disclosed, altered, or destroyed by breach of any of our   physical, technical, or managerial safeguards. If my contact learns of a   security systems breach, then we may attempt to notify you   electronically so that you can take appropriate protective steps.   my contact may post a notice on the my contact Site or through the my contact   Service if a security breach occurs. </p>
<h4>Our Commitment To Childrens' Privacy</h4>
<p>Protecting the privacy of young children is especially important. For   that reason, my contact does not knowingly collect or maintain Personally   Identifiable Information or non-personally-identifiable information on   the my contact Site or my contact Service from persons under 16 years of   age, and no part of the my contact Service is directed to or intended to   be used by persons under 16. If you are under 16 years of age, then   please do not use the my contact Service or access the my contact Site at   any time or in any manner. If my contact learns that Personally   Identifiable Information of persons under 16 years of age has been   collected on the my contact Site or my contact Service, then my contact may   deactivate the account and/or make the status submissions inaccessible.   And always, think of the children! </p>
<h4>Special Note to International Users</h4>
<p>The my contact Site and Service are hosted in the United States and are   intended for and directed to users in the United States. If you are a   user accessing the my contact Site and Service from the European Union,   Asia, or any other region with laws or regulations governing personal   data collection, use, and disclosure, that differ from United States   laws, please be advised that through your continued use of the my contact   Site and Service, which are governed by California law, this Privacy   Policy, and our Terms of Service, you are transferring your personal   information to the United States and you expressly consent to that   transfer and consent to be governed by California law for these   purposes. </p>
<h4>In the Event of Merger or Sale</h4>
<p>In the event that my contact is acquired by or merged with a third   party entity, we reserve the right to transfer or assign the information   we have collected from our users as part of such merger, acquisition,   sale, or other change of control. </p>
<h4>Changes and updates to this Privacy Notice</h4>
<p>This Privacy Policy may be revised periodically and this will be   reflected by the &quot;effective date&quot; below. Please revisit this page to   stay aware of any changes. Your continued use of the my contact Site and   my contact Service constitutes your agreement to this Privacy Policy and   any amendments. </p>
<br />
<p>Date Last Modified:</p>
<p>This Privacy Notice was last modified January 21, 2015.</p>

 		
          </div>
        </div>
      </div>
    </section>

<BR><BR>

<center>
<P> <a href="#section-0">Sign Up</a> | <a href="#section-1">How It Works</a> | <!-- <a href="#section-3">News</a> | <a href="#section-4">Press</a> | --> <a href="#section-4">Contact Us</a> | <a href="tos.asp">Terms & Conditions</a> | <a href="tos.asp">Privacy Policy</a> | <a href="sitemap.asp">Site Map</a>
<font color="ff9900"><BR> Patents Pending | &copy; Copyright 2016 </font></P>
</center>


<P><BR><P><BR>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/scrolling-nav.js"></script>

</font>
</body>
</html>